name: coverage

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Generate coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
